// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blobs_queries.sql

package queries

import (
	"context"
)

const createLargeBlob = `-- name: CreateLargeBlob :one
INSERT INTO blobs (key, meta, data, large)
VALUES (?, ?, X'', 1)
RETURNING key, meta, data, large
`

type CreateLargeBlobParams struct {
	Key  string `json:"key"`
	Meta string `json:"meta"`
}

func (q *Queries) CreateLargeBlob(ctx context.Context, arg CreateLargeBlobParams) (Blob, error) {
	row := q.db.QueryRowContext(ctx, createLargeBlob, arg.Key, arg.Meta)
	var i Blob
	err := row.Scan(
		&i.Key,
		&i.Meta,
		&i.Data,
		&i.Large,
	)
	return i, err
}

const createSmallBlob = `-- name: CreateSmallBlob :one
INSERT INTO blobs (key, meta, data, large)
VALUES (?, ?, ?, 0)
RETURNING key, meta, data, large
`

type CreateSmallBlobParams struct {
	Key  string `json:"key"`
	Meta string `json:"meta"`
	Data []byte `json:"data"`
}

func (q *Queries) CreateSmallBlob(ctx context.Context, arg CreateSmallBlobParams) (Blob, error) {
	row := q.db.QueryRowContext(ctx, createSmallBlob, arg.Key, arg.Meta, arg.Data)
	var i Blob
	err := row.Scan(
		&i.Key,
		&i.Meta,
		&i.Data,
		&i.Large,
	)
	return i, err
}

const deleteLargeBlob = `-- name: DeleteLargeBlob :one
DELETE FROM blobs
WHERE key = ? AND large = 1
RETURNING key
`

func (q *Queries) DeleteLargeBlob(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, deleteLargeBlob, key)
	var key_2 string
	err := row.Scan(&key_2)
	return key_2, err
}

const deleteSmallBlob = `-- name: DeleteSmallBlob :exec
DELETE FROM blobs
WHERE key = ? AND large = 0
`

func (q *Queries) DeleteSmallBlob(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteSmallBlob, key)
	return err
}

const getLargeBlob = `-- name: GetLargeBlob :one
SELECT key, meta, data, large
FROM blobs
WHERE key = ? AND large = 1
`

func (q *Queries) GetLargeBlob(ctx context.Context, key string) (Blob, error) {
	row := q.db.QueryRowContext(ctx, getLargeBlob, key)
	var i Blob
	err := row.Scan(
		&i.Key,
		&i.Meta,
		&i.Data,
		&i.Large,
	)
	return i, err
}

const getSmallBlob = `-- name: GetSmallBlob :one
SELECT key, meta, data, large
FROM blobs
WHERE key = ? AND large = 0
`

func (q *Queries) GetSmallBlob(ctx context.Context, key string) (Blob, error) {
	row := q.db.QueryRowContext(ctx, getSmallBlob, key)
	var i Blob
	err := row.Scan(
		&i.Key,
		&i.Meta,
		&i.Data,
		&i.Large,
	)
	return i, err
}
