// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql"
)

type Admin struct {
	ID           int64  `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	CreatedAt    string `json:"created_at"`
}

type AdminSession struct {
	TokenHash []byte `json:"token_hash"`
	AdminID   int64  `json:"admin_id"`
	ExpiresAt string `json:"expires_at"`
	CreatedAt string `json:"created_at"`
}

type Queue struct {
	ID               int64          `json:"id"`
	Data             []byte         `json:"data"`
	Reference        string         `json:"reference"`
	EnqueuedAt       string         `json:"enqueued_at"`
	UnavailableUntil string         `json:"unavailable_until"`
	ProcessedAt      sql.NullString `json:"processed_at"`
}
