// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queue_queries.sql

package queries

import (
	"context"
	"database/sql"
)

const claimBatch = `-- name: ClaimBatch :many
UPDATE queue
SET unavailable_until = strftime('%Y-%m-%d %H:%M:%f', 'now', '+' || CAST(? AS TEXT) || ' seconds')
WHERE id IN (
    SELECT pending.id
    FROM queue AS pending
    WHERE pending.reference = ?
      AND pending.processed_at IS NULL
      AND pending.unavailable_until <= strftime('%Y-%m-%d %H:%M:%f', 'now')
    ORDER BY pending.enqueued_at, pending.id
    LIMIT 50
)
RETURNING id, data, reference, enqueued_at, unavailable_until, processed_at
`

type ClaimBatchParams struct {
	Column1   string `json:"column_1"`
	Reference string `json:"reference"`
}

func (q *Queries) ClaimBatch(ctx context.Context, arg ClaimBatchParams) ([]Queue, error) {
	rows, err := q.db.QueryContext(ctx, claimBatch, arg.Column1, arg.Reference)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Queue{}
	for rows.Next() {
		var i Queue
		if err := rows.Scan(
			&i.ID,
			&i.Data,
			&i.Reference,
			&i.EnqueuedAt,
			&i.UnavailableUntil,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueue = `-- name: Enqueue :one
INSERT INTO queue (data, reference)
VALUES (?, ?)
RETURNING id, data, reference, enqueued_at, unavailable_until, processed_at
`

type EnqueueParams struct {
	Data      []byte `json:"data"`
	Reference string `json:"reference"`
}

func (q *Queries) Enqueue(ctx context.Context, arg EnqueueParams) (Queue, error) {
	row := q.db.QueryRowContext(ctx, enqueue, arg.Data, arg.Reference)
	var i Queue
	err := row.Scan(
		&i.ID,
		&i.Data,
		&i.Reference,
		&i.EnqueuedAt,
		&i.UnavailableUntil,
		&i.ProcessedAt,
	)
	return i, err
}

const markQueueDead = `-- name: MarkQueueDead :exec
UPDATE queue
SET unavailable_until = '9999-01-01 00:00:00'
WHERE id = ? AND processed_at IS NULL
`

func (q *Queries) MarkQueueDead(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markQueueDead, id)
	return err
}

const markQueueDone = `-- name: MarkQueueDone :exec
UPDATE queue
SET processed_at = CURRENT_TIMESTAMP
WHERE id = ? AND processed_at IS NULL
`

func (q *Queries) MarkQueueDone(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markQueueDone, id)
	return err
}

const retryQueue = `-- name: RetryQueue :exec
UPDATE queue
SET unavailable_until = strftime('%Y-%m-%d %H:%M:%f', 'now', '+' || ? || ' seconds')
WHERE id = ? AND processed_at IS NULL
`

type RetryQueueParams struct {
	Column1 sql.NullString `json:"column_1"`
	ID      int64          `json:"id"`
}

func (q *Queries) RetryQueue(ctx context.Context, arg RetryQueueParams) error {
	_, err := q.db.ExecContext(ctx, retryQueue, arg.Column1, arg.ID)
	return err
}
